Repository doctrine/common, pull requests merged in 2022-08, with the labels that each got.

#967 Add doctrine/collections to dev dependencies
  composer.json
Labels: Bug

#969 Fix PHPUnit deprecations
  tests/Doctrine/Tests/Common/Proxy/InvokationSpy.php
  tests/Doctrine/Tests/Common/Proxy/ProxyLogicTest.php
  tests/Doctrine/Tests/Common/Proxy/ProxyLogicTypedPropertiesTest.php
Labels: Improvement

#970 Support void return type for __clone magic method
  lib/Doctrine/Common/Proxy/ProxyGenerator.php
  tests/Doctrine/Tests/Common/Proxy/Php8MagicCloneClass.php
  tests/Doctrine/Tests/Common/Proxy/ProxyGeneratorTest.php
Labels: Bug

#966 Support new in initializers
  lib/Doctrine/Common/Proxy/ProxyGenerator.php
  tests/Doctrine/Tests/Common/Proxy/PHP81NewInInitializers.php
  tests/Doctrine/Tests/Common/Proxy/ProxyGeneratorTest.php
Labels: New Feature

#979 Remove Ant config
  .gitattributes
  .gitignore
  build.xml
Labels: Internal

#978 Remove test suite bootstrap file
  phpunit.xml.dist
  tests/Doctrine/Tests/TestInit.php
Labels: Internal

#981 Fix build with slevomat/coding-standard 8
  phpcs.xml.dist
  src/Proxy/Exception/InvalidArgumentException.php
  src/Proxy/ProxyGenerator.php
Labels: Improvement
